{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyNNYqm0LL3IHaCm9WFcgzp/"
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "execution_count": 2,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "M6rPi65x02Fx",
        "outputId": "6986b885-7487-4b74-e99d-e47bd56c948e"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "{\n",
            "  \"Barracuda, California\": {\n",
            "    \"sci\": \"Sphyraena argentea\",\n",
            "    \"range\": \"Barracuda range from Cabo San Lucas, Mexico to Puget Sound in Washington State. The geographic range of barracuda is highly influenced by water temperature. …\",\n",
            "    \"habitat\": \"Barracuda can range from the pelagic environment to nearshore kelp beds and rocky reefs. They are commonly found from the surface to 120 feet (ft) (36 meters (m)) in depth.\",\n",
            "    \"factors\": {\n",
            "      \"sens\": {\n",
            "        \"Habitat\": 2.27,\n",
            "        \"Prey\": 2.33,\n",
            "        \"Adult mobility\": 1.13,\n",
            "        \"Early dispersal\": 2.27,\n",
            "        \"Early survival\": 2.33,\n",
            "        \"Reproduction\": 1.73,\n",
            "        \"Spawning cycle\": 2.13,\n",
            "        \"Temperature\": 1.93,\n",
            "        \"Ocean acidification\": 1.2,\n",
            "        \"Pop. growth\": 2.33,\n",
            "        \"Stock status\": 2.2,\n",
            "        \"Other stressors\": 1.27\n",
            "      },\n",
            "      \"exp\": {\n",
            "        \"SST\": 3.27,\n",
            "        \"Ocean pH\": 3.73,\n",
            "        \"Bottom oxygen\": 2.53,\n",
            "        \"Upwelling\": 2.33,\n",
            "        \"Sea level\": 1.87,\n",
            "        \"Salinity\": 2.75,\n",
            "        \"Air temp\": 2.4,\n",
            "        \"Precip.\": 1.73\n",
            "      }\n",
            "    },\n",
            "    \"pounds\": {}\n",
            "  },\n",
            "  \"Bonito, Pacific\": {\n",
            "    \"sci\": \"Sarda chiliensis\",\n",
            "    \"range\": \"Despite the geographic separation of the Pacific bonito’s population range (i.e., a gap from the central coast of Mexico south to Panama), the species has been reported occurring from southern Alaska to northern Chile, with the northern population of Bonito typically centered between southern California and central Baja California.\",\n",
            "    \"habitat\": \"Bonito can be found at very shallow depths in nearshore environments in kelp forests, bays and the coastal zone up to depths of 300 ft (91 m) offshore in the pelagic environment. …\",\n",
            "    \"factors\": {\n",
            "      \"sens\": {\n",
            "        \"Habitat\": 2.28,\n",
            "        \"Prey\": 1.56,\n",
            "        \"Adult mobility\": 1.08,\n",
            "        \"Early dispersal\": 2.28,\n",
            "        \"Early survival\": 2.08,\n",
            "        \"Reproduction\": 1.76,\n",
            "        \"Spawning cycle\": 2.72,\n",
            "        \"Temperature\": 1.48,\n",
            "        \"Ocean acidification\": 1.2,\n",
            "        \"Pop. growth\": 1.4,\n",
            "        \"Stock status\": 1.48,\n",
            "        \"Other stressors\": 1.44\n",
            "      },\n",
            "      \"exp\": {\n",
            "        \"SST\": 2.75,\n",
            "        \"Ocean pH\": 2.8,\n",
            "        \"Bottom oxygen\": 2.8,\n",
            "        \"Upwelling\": 2.32,\n",
            "        \"Sea level\": 1.64,\n",
            "        \"Salinity\": 2.32,\n",
            "        \"Air temp\": 1.88,\n",
            "        \"Precip.\": 1.36\n",
            "      }\n",
            "    },\n",
            "    \"pounds\": {}\n",
            "  },\n",
            "  \"Crab, Dungeness\": {\n",
            "    \"sci\": \"Metacarcinus magister\",\n",
            "    \"range\": \"From Alaska to Santa Barbara, CA. Dungeness crab rarely occur south of Point Conception.\",\n",
            "    \"habitat\": \"Habitat generalist. Prefers sandy-bottom habitats. Found between 38-65 F (3-18 C deg). At depths ranging from intertidal to 300 ft (>90m). Prefer salinities ranging 25-32 ppt. …\",\n",
            "    \"factors\": {\n",
            "      \"sens\": {\n",
            "        \"Habitat\": 2.75,\n",
            "        \"Prey\": 1.6,\n",
            "        \"Adult mobility\": 2.73,\n",
            "        \"Early dispersal\": 1.4,\n",
            "        \"Early survival\": 3.53,\n",
            "        \"Reproduction\": 3.07,\n",
            "        \"Spawning cycle\": 2.53,\n",
            "        \"Temperature\": 3.47,\n",
            "        \"Ocean acidification\": 3.87,\n",
            "        \"Pop. growth\": 2.0,\n",
            "        \"Stock status\": 2.0,\n",
            "        \"Other stressors\": 2.2\n",
            "      },\n",
            "      \"exp\": {\n",
            "        \"SST\": 3.53,\n",
            "        \"Ocean pH\": 3.93,\n",
            "        \"Bottom oxygen\": 3.33,\n",
            "        \"Upwelling\": 3.6,\n",
            "        \"Sea level\": 3.0,\n",
            "        \"Salinity\": 3.47,\n",
            "        \"Air temp\": 2.8,\n",
            "        \"Precip.\": 2.6\n",
            "      }\n",
            "    },\n",
            "    \"pounds\": {}\n",
            "  },\n",
            "  \"Croaker, white\": {\n",
            "    \"sci\": \"Genyonemus lineatus\",\n",
            "    \"range\": \"White croaker have a large range from Barkley Sound, British Columbia to Bahia Magdalena, Baja California Sur. They are most abundant south of San Francisco Bay and north of Baja California.\",\n",
            "    \"habitat\": \"See above.. White croaker are most abundant in the surf zone (10 feet (ft) or 3 meters (m)) to about 130 m (426 ft) but may be found at depths up to 238 m (781 ft) (Love 2011). …\",\n",
            "    \"factors\": {\n",
            "      \"sens\": {\n",
            "        \"Habitat\": 1.73,\n",
            "        \"Prey\": 2.53,\n",
            "        \"Adult mobility\": 1.33,\n",
            "        \"Early dispersal\": 2.25,\n",
            "        \"Early survival\": 2.47,\n",
            "        \"Reproduction\": 1.87,\n",
            "        \"Spawning cycle\": 1.53,\n",
            "        \"Temperature\": 1.53,\n",
            "        \"Ocean acidification\": 2.8,\n",
            "        \"Pop. growth\": 2.47,\n",
            "        \"Stock status\": 2.93,\n",
            "        \"Other stressors\": 2.0\n",
            "      },\n",
            "      \"exp\": {\n",
            "        \"SST\": 3.13,\n",
            "        \"Ocean pH\": 3.73,\n",
            "        \"Bottom oxygen\": 2.2,\n",
            "        \"Upwelling\": 2.07,\n",
            "        \"Sea level\": 2.8,\n",
            "        \"Salinity\": 2.67,\n",
            "        \"Air temp\": 2.67,\n",
            "        \"Precip.\": 2.2\n",
            "      }\n",
            "    },\n",
            "    \"pounds\": {}\n",
            "  },\n",
            "  \"Halibut, California\": {\n",
            "    \"sci\": \"Paralichthys californicus\",\n",
            "    \"range\": \"Ranges from Quillayute River in northern Washington to Cabo Falsa (22°50’N) in southern Baja California, Mexico. Most commonly encountered from Bodega Bay, northern California (Sonoma County) to Bahía de San Quintín, northern Baja California\",\n",
            "    \"habitat\": \"Adults use soft bottom substrate (sand, mud) and concentrate in or near bays, estuaries, coastal areas shallower than 60m. Depth can reach ~300m.\",\n",
            "    \"factors\": {\n",
            "      \"sens\": {\n",
            "        \"Habitat\": 2.75,\n",
            "        \"Prey\": 1.33,\n",
            "        \"Adult mobility\": 1.6,\n",
            "        \"Early dispersal\": 1.93,\n",
            "        \"Early survival\": 1.87,\n",
            "        \"Reproduction\": 1.8,\n",
            "        \"Spawning cycle\": 1.27,\n",
            "        \"Temperature\": 1.67,\n",
            "        \"Ocean acidification\": 1.47,\n",
            "        \"Pop. growth\": 2.33,\n",
            "        \"Stock status\": 2.0,\n",
            "        \"Other stressors\": 1.8\n",
            "      },\n",
            "      \"exp\": {\n",
            "        \"SST\": 3.07,\n",
            "        \"Ocean pH\": 3.67,\n",
            "        \"Bottom oxygen\": 2.87,\n",
            "        \"Upwelling\": 1.87,\n",
            "        \"Sea level\": 3.47,\n",
            "        \"Salinity\": 2.27,\n",
            "        \"Air temp\": 2.33,\n",
            "        \"Precip.\": 2.47\n",
            "      }\n",
            "    },\n",
            "    \"pounds\": {}\n",
            "  },\n",
            "  \"Jacksmelt\": {\n",
            "    \"sci\": \"Atherinopsis californiensis\",\n",
            "    \"range\": \"The geographic range of jacksmelt extends from Coos Bay, Oregon to Magdalena Bay, Baja California, Mexico\",\n",
            "    \"habitat\": \"It is common to observe pier and shore anglers catching jacksmelt when water temperatures are elevated above 15.6°C (60°F). …\",\n",
            "    \"factors\": {\n",
            "      \"sens\": {\n",
            "        \"Habitat\": 2.33,\n",
            "        \"Prey\": 1.87,\n",
            "        \"Adult mobility\": 1.73,\n",
            "        \"Early dispersal\": 3.33,\n",
            "        \"Early survival\": 2.07,\n",
            "        \"Reproduction\": 1.73,\n",
            "        \"Spawning cycle\": 1.4,\n",
            "        \"Temperature\": 1.73,\n",
            "        \"Ocean acidification\": 1.2,\n",
            "        \"Pop. growth\": 2.0,\n",
            "        \"Stock status\": 1.53,\n",
            "        \"Other stressors\": 2.67\n",
            "      },\n",
            "      \"exp\": {\n",
            "        \"SST\": 3.4,\n",
            "        \"Ocean pH\": 3.73,\n",
            "        \"Bottom oxygen\": 2.93,\n",
            "        \"Upwelling\": 2.4,\n",
            "        \"Sea level\": 3.47,\n",
            "        \"Salinity\": 2.87,\n",
            "        \"Air temp\": 3.27,\n",
            "        \"Precip.\": 2.47\n",
            "      }\n",
            "    },\n",
            "    \"pounds\": {}\n",
            "  },\n",
            "  \"Lobster, California spiny\": {\n",
            "    \"sci\": \"Panulirus interruptus\",\n",
            "    \"range\": \"Ranges from Monterey, CA to Magdalena Bay, Baja California. Center of spiny lobster range is in Mexico, productivity and desnity is highest there. With increasing temperatures comes larval settlement further and further north.\",\n",
            "    \"habitat\": \"Occupy shallow reefs in summer-fall where surface waters are warm and storm activity low. Move to deeper water when winter swells and storms begin and surface water is cool. Adults require hard substrate for shelter.\",\n",
            "    \"factors\": {\n",
            "      \"sens\": {\n",
            "        \"Habitat\": 3.33,\n",
            "        \"Prey\": 1.27,\n",
            "        \"Adult mobility\": 2.4,\n",
            "        \"Early dispersal\": 1.0,\n",
            "        \"Early survival\": 3.2,\n",
            "        \"Reproduction\": 3.0,\n",
            "        \"Spawning cycle\": 3.73,\n",
            "        \"Temperature\": 3.25,\n",
            "        \"Ocean acidification\": 2.8,\n",
            "        \"Pop. growth\": 3.25,\n",
            "        \"Stock status\": 2.27,\n",
            "        \"Other stressors\": 2.6\n",
            "      },\n",
            "      \"exp\": {\n",
            "        \"SST\": 3.13,\n",
            "        \"Ocean pH\": 3.73,\n",
            "        \"Bottom oxygen\": 2.87,\n",
            "        \"Upwelling\": 3.33,\n",
            "        \"Sea level\": 2.93,\n",
            "        \"Salinity\": 2.73,\n",
            "        \"Air temp\": 2.27,\n",
            "        \"Precip.\": 1.93\n",
            "      }\n",
            "    },\n",
            "    \"pounds\": {}\n",
            "  },\n",
            "  \"Prawn, ridgeback\": {\n",
            "    \"sci\": \"Sicyonia ingentis\",\n",
            "    \"range\": \"Northern boundary at Monterey Bay, CA (36.9 N). Southern boundary is Isla Maria Madre, Mexico (latitude 21.6 N)\",\n",
            "    \"habitat\": \"Soft bottom habitat. Tolerate a range of temperature (4-30 deg C) and range of salinity (33-35 ppt). Distributed between inner to outer continental shelf. Depth 145m. Located south of Pt Conception (35N). Adults found further offshore.\",\n",
            "    \"factors\": {\n",
            "      \"sens\": {\n",
            "        \"Habitat\": 1.27,\n",
            "        \"Prey\": 1.13,\n",
            "        \"Adult mobility\": 2.8,\n",
            "        \"Early dispersal\": 2.25,\n",
            "        \"Early survival\": 2.07,\n",
            "        \"Reproduction\": 1.8,\n",
            "        \"Spawning cycle\": 2.53,\n",
            "        \"Temperature\": 2.0,\n",
            "        \"Ocean acidification\": 2.4,\n",
            "        \"Pop. growth\": 1.8,\n",
            "        \"Stock status\": 1.87,\n",
            "        \"Other stressors\": 1.4\n",
            "      },\n",
            "      \"exp\": {\n",
            "        \"SST\": 2.75,\n",
            "        \"Ocean pH\": 3.25,\n",
            "        \"Bottom oxygen\": 2.8,\n",
            "        \"Upwelling\": 2.87,\n",
            "        \"Sea level\": 1.93,\n",
            "        \"Salinity\": 3.2,\n",
            "        \"Air temp\": 1.47,\n",
            "        \"Precip.\": 1.53\n",
            "      }\n",
            "    },\n",
            "    \"pounds\": {}\n",
            "  },\n",
            "  \"Prawn, spot\": {\n",
            "    \"sci\": \"Pandalus platyceros\",\n",
            "    \"range\": \"Reported as from Unalaska, AK to San Diego, CA, but during 1999 to 2001, Spot Prawns were caught in experimental fisheries in Ensenada, Mexico, suggesting that their range may extend as far south as Punta Eugenia in central Baja California, Mexico. …\",\n",
            "    \"habitat\": \"Adults inhabit depths ranging from 150 to 1,600 feet and are associated with rocky bottoms including vertical rock walls, bedrock, boulder, cobble, or mixed bottom habitat types and with drifting macrophytes\",\n",
            "    \"factors\": {\n",
            "      \"sens\": {\n",
            "        \"Habitat\": 2.8,\n",
            "        \"Prey\": 1.07,\n",
            "        \"Adult mobility\": 2.87,\n",
            "        \"Early dispersal\": 2.6,\n",
            "        \"Early survival\": 2.6,\n",
            "        \"Reproduction\": 2.13,\n",
            "        \"Spawning cycle\": 3.73,\n",
            "        \"Temperature\": 2.75,\n",
            "        \"Ocean acidification\": 3.33,\n",
            "        \"Pop. growth\": 1.67,\n",
            "        \"Stock status\": 1.6,\n",
            "        \"Other stressors\": 1.73\n",
            "      },\n",
            "      \"exp\": {\n",
            "        \"SST\": 3.25,\n",
            "        \"Ocean pH\": 2.53,\n",
            "        \"Bottom oxygen\": 3.0,\n",
            "        \"Upwelling\": 2.47,\n",
            "        \"Sea level\": 1.6,\n",
            "        \"Salinity\": 2.25,\n",
            "        \"Air temp\": 1.4,\n",
            "        \"Precip.\": 1.27\n",
            "      }\n",
            "    },\n",
            "    \"pounds\": {}\n",
            "  },\n",
            "  \"Sea urchin, red\": {\n",
            "    \"sci\": \"Mesocentrotus franciscanus\",\n",
            "    \"range\": \"Found in Gulf of Alaska to Baja California. Found statewide in CA. Fewer urchins are found in the sea otter zone from San Francisco to Point Conception because of predation\",\n",
            "    \"habitat\": \"Rocky habitats, rock piles, shallow intertidal to depths of 300 ft.\",\n",
            "    \"factors\": {\n",
            "      \"sens\": {\n",
            "        \"Habitat\": 2.4,\n",
            "        \"Prey\": 2.0,\n",
            "        \"Adult mobility\": 2.75,\n",
            "        \"Early dispersal\": 1.27,\n",
            "        \"Early survival\": 3.0,\n",
            "        \"Reproduction\": 2.07,\n",
            "        \"Spawning cycle\": 2.27,\n",
            "        \"Temperature\": 2.53,\n",
            "        \"Ocean acidification\": 3.75,\n",
            "        \"Pop. growth\": 2.6,\n",
            "        \"Stock status\": 2.2,\n",
            "        \"Other stressors\": 2.87\n",
            "      },\n",
            "      \"exp\": {\n",
            "        \"SST\": 2.87,\n",
            "        \"Ocean pH\": 3.6,\n",
            "        \"Bottom oxygen\": 2.4,\n",
            "        \"Upwelling\": 2.87,\n",
            "        \"Sea level\": 2.13,\n",
            "        \"Salinity\": 2.2,\n",
            "        \"Air temp\": 2.27,\n",
            "        \"Precip.\": 1.73\n",
            "      }\n",
            "    },\n",
            "    \"pounds\": {}\n",
            "  },\n",
            "  \"Seabass, white\": {\n",
            "    \"sci\": \"Atractoscion nobilis\",\n",
            "    \"range\": \"Throughout California and Mexico. During warm water events they have been found in Alaska\",\n",
            "    \"habitat\": \"Habitat for adult is over rocky substrate in or near large kelp beds. Can be found several miles offshore swimming near surface during spring and summer\",\n",
            "    \"factors\": {\n",
            "      \"sens\": {\n",
            "        \"Habitat\": 2.72,\n",
            "        \"Prey\": 1.64,\n",
            "        \"Adult mobility\": 1.36,\n",
            "        \"Early dispersal\": 2.32,\n",
            "        \"Early survival\": 2.52,\n",
            "        \"Reproduction\": 2.32,\n",
            "        \"Spawning cycle\": 2.36,\n",
            "        \"Temperature\": 2.16,\n",
            "        \"Ocean acidification\": 1.32,\n",
            "        \"Pop. growth\": 2.25,\n",
            "        \"Stock status\": 2.52,\n",
            "        \"Other stressors\": 2.17\n",
            "      },\n",
            "      \"exp\": {\n",
            "        \"SST\": 3.32,\n",
            "        \"Ocean pH\": 3.24,\n",
            "        \"Bottom oxygen\": 2.68,\n",
            "        \"Upwelling\": 2.2,\n",
            "        \"Sea level\": 2.16,\n",
            "        \"Salinity\": 2.28,\n",
            "        \"Air temp\": 2.16,\n",
            "        \"Precip.\": 2.12\n",
            "      }\n",
            "    },\n",
            "    \"pounds\": {}\n",
            "  },\n",
            "  \"Shark, Pacific angel\": {\n",
            "    \"sci\": \"Squatina californica\",\n",
            "    \"range\": \"Pacific angel shark range from Vancouver Island to the Gulf of California, and Peru.\",\n",
            "    \"habitat\": \"Pacific angel shark are bottom dwellers that typically live in muddy and sandy habitats on the continental shelf. They are common at depths of 15 to 40 m (49 to 131 ft) but have been observed as deep as 215 m (328 ft). …\",\n",
            "    \"factors\": {\n",
            "      \"sens\": {\n",
            "        \"Habitat\": 1.93,\n",
            "        \"Prey\": 2.07,\n",
            "        \"Adult mobility\": 1.8,\n",
            "        \"Early dispersal\": 3.0,\n",
            "        \"Early survival\": 1.07,\n",
            "        \"Reproduction\": 1.47,\n",
            "        \"Spawning cycle\": 1.8,\n",
            "        \"Temperature\": 1.6,\n",
            "        \"Ocean acidification\": 1.27,\n",
            "        \"Pop. growth\": 3.67,\n",
            "        \"Stock status\": 1.93,\n",
            "        \"Other stressors\": 1.8\n",
            "      },\n",
            "      \"exp\": {\n",
            "        \"SST\": 1.93,\n",
            "        \"Ocean pH\": 3.13,\n",
            "        \"Bottom oxygen\": 2.81,\n",
            "        \"Upwelling\": 1.93,\n",
            "        \"Sea level\": 2.4,\n",
            "        \"Salinity\": 2.07,\n",
            "        \"Air temp\": 1.87,\n",
            "        \"Precip.\": 1.87\n",
            "      }\n",
            "    },\n",
            "    \"pounds\": {}\n",
            "  },\n",
            "  \"Shark, brown smoothhound\": {\n",
            "    \"sci\": \"Mustelus henlei\",\n",
            "    \"range\": \"Brown smoothhound are found from northern Washington to the Gulf of California in the northern hemisphere and from Costa Rica to Peru\",\n",
            "    \"habitat\": \"Brown smoothhound are epibenthic, dwelling on or just above the seafloor where they spend most of their time foraging for prey. …\",\n",
            "    \"factors\": {\n",
            "      \"sens\": {\n",
            "        \"Habitat\": 2.67,\n",
            "        \"Prey\": 1.67,\n",
            "        \"Adult mobility\": 1.8,\n",
            "        \"Early dispersal\": 3.25,\n",
            "        \"Early survival\": 1.73,\n",
            "        \"Reproduction\": 2.6,\n",
            "        \"Spawning cycle\": 3.67,\n",
            "        \"Temperature\": 1.8,\n",
            "        \"Ocean acidification\": 2.0,\n",
            "        \"Pop. growth\": 2.47,\n",
            "        \"Stock status\": 1.33,\n",
            "        \"Other stressors\": 2.0\n",
            "      },\n",
            "      \"exp\": {\n",
            "        \"SST\": 3.27,\n",
            "        \"Ocean pH\": 3.73,\n",
            "        \"Bottom oxygen\": 3.47,\n",
            "        \"Upwelling\": 2.07,\n",
            "        \"Sea level\": 3.33,\n",
            "        \"Salinity\": 3.47,\n",
            "        \"Air temp\": 2.87,\n",
            "        \"Precip.\": 2.53\n",
            "      }\n",
            "    },\n",
            "    \"pounds\": {}\n",
            "  },\n",
            "  \"Sheephead, California\": {\n",
            "    \"sci\": \"Semicossyphus pulcher\",\n",
            "    \"range\": \"Could be long-term positive responses by sheephead populations migrating into warm water regimes, as their northern range to Monterey Bay is likely a relatively modern phenomenon as increasing warming events may increase the range of larval dispersal and survivorship (Cowen 1986; Braje et al. …\",\n",
            "    \"habitat\": \"Adults live in kelp forests and rocky reef habitats\",\n",
            "    \"factors\": {\n",
            "      \"sens\": {\n",
            "        \"Habitat\": 3.6,\n",
            "        \"Prey\": 1.33,\n",
            "        \"Adult mobility\": 2.6,\n",
            "        \"Early dispersal\": 2.4,\n",
            "        \"Early survival\": 2.6,\n",
            "        \"Reproduction\": 1.8,\n",
            "        \"Spawning cycle\": 2.33,\n",
            "        \"Temperature\": 3.0,\n",
            "        \"Ocean acidification\": 2.67,\n",
            "        \"Pop. growth\": 2.93,\n",
            "        \"Stock status\": 3.0,\n",
            "        \"Other stressors\": 2.25\n",
            "      },\n",
            "      \"exp\": {\n",
            "        \"SST\": 2.75,\n",
            "        \"Ocean pH\": 3.6,\n",
            "        \"Bottom oxygen\": 2.53,\n",
            "        \"Upwelling\": 2.2,\n",
            "        \"Sea level\": 2.47,\n",
            "        \"Salinity\": 2.4,\n",
            "        \"Air temp\": 1.8,\n",
            "        \"Precip.\": 2.0\n",
            "      }\n",
            "    },\n",
            "    \"pounds\": {}\n",
            "  },\n",
            "  \"Squid, market\": {\n",
            "    \"sci\": \"Doryteuthis opalescens\",\n",
            "    \"range\": \"Ranges from southeast Alaska to Baja, Mexico\",\n",
            "    \"habitat\": \"Market squid are a Coastal Pelagic Species, habitat is based on a temperature range and oxygen minimum zone. …\",\n",
            "    \"factors\": {\n",
            "      \"sens\": {\n",
            "        \"Habitat\": 2.25,\n",
            "        \"Prey\": 1.73,\n",
            "        \"Adult mobility\": 1.53,\n",
            "        \"Early dispersal\": 1.4,\n",
            "        \"Early survival\": 3.2,\n",
            "        \"Reproduction\": 2.2,\n",
            "        \"Spawning cycle\": 1.8,\n",
            "        \"Temperature\": 2.75,\n",
            "        \"Ocean acidification\": 2.73,\n",
            "        \"Pop. growth\": 1.2,\n",
            "        \"Stock status\": 1.67,\n",
            "        \"Other stressors\": 1.33\n",
            "      },\n",
            "      \"exp\": {\n",
            "        \"SST\": 3.4,\n",
            "        \"Ocean pH\": 3.73,\n",
            "        \"Bottom oxygen\": 3.73,\n",
            "        \"Upwelling\": 3.73,\n",
            "        \"Sea level\": 1.73,\n",
            "        \"Salinity\": 2.47,\n",
            "        \"Air temp\": 1.87,\n",
            "        \"Precip.\": 1.8\n",
            "      }\n",
            "    },\n",
            "    \"pounds\": {}\n",
            "  },\n",
            "  \"Surfperch, barred\": {\n",
            "    \"sci\": \"Amphistichus argenteus\",\n",
            "    \"range\": \"The geographic range of barred surfperch extends from Bodega Bay (Sonoma County) to central Baja California, Mexico (Love and Passarelli 2020).\",\n",
            "    \"habitat\": \"See above\",\n",
            "    \"factors\": {\n",
            "      \"sens\": {\n",
            "        \"Habitat\": 1.94,\n",
            "        \"Prey\": 2.07,\n",
            "        \"Adult mobility\": 2.4,\n",
            "        \"Early dispersal\": 3.38,\n",
            "        \"Early survival\": 2.47,\n",
            "        \"Reproduction\": 2.07,\n",
            "        \"Spawning cycle\": 3.07,\n",
            "        \"Temperature\": 2.27,\n",
            "        \"Ocean acidification\": 2.47,\n",
            "        \"Pop. growth\": 1.93,\n",
            "        \"Stock status\": 1.27,\n",
            "        \"Other stressors\": 1.87\n",
            "      },\n",
            "      \"exp\": {\n",
            "        \"SST\": 3.2,\n",
            "        \"Ocean pH\": 3.6,\n",
            "        \"Bottom oxygen\": 2.47,\n",
            "        \"Upwelling\": 2.73,\n",
            "        \"Sea level\": 3.13,\n",
            "        \"Salinity\": 3.07,\n",
            "        \"Air temp\": 2.2,\n",
            "        \"Precip.\": 2.27\n",
            "      }\n",
            "    },\n",
            "    \"pounds\": {}\n",
            "  },\n",
            "  \"Surfperch, redtail\": {\n",
            "    \"sci\": \"Amphistichus rhodoterus\",\n",
            "    \"range\": \"Redtail surfperch range from Vancouver Island, British Columbia to Avila Beach (San Luis Obispo County) but are uncommon south of San Mateo County.\",\n",
            "    \"habitat\": \"See above\",\n",
            "    \"factors\": {\n",
            "      \"sens\": {\n",
            "        \"Habitat\": 1.67,\n",
            "        \"Prey\": 2.4,\n",
            "        \"Adult mobility\": 2.0,\n",
            "        \"Early dispersal\": 3.53,\n",
            "        \"Early survival\": 2.33,\n",
            "        \"Reproduction\": 2.07,\n",
            "        \"Spawning cycle\": 3.07,\n",
            "        \"Temperature\": 2.07,\n",
            "        \"Ocean acidification\": 2.67,\n",
            "        \"Pop. growth\": 2.0,\n",
            "        \"Stock status\": 2.8,\n",
            "        \"Other stressors\": 2.27\n",
            "      },\n",
            "      \"exp\": {\n",
            "        \"SST\": 2.8,\n",
            "        \"Ocean pH\": 3.2,\n",
            "        \"Bottom oxygen\": 2.4,\n",
            "        \"Upwelling\": 2.13,\n",
            "        \"Sea level\": 2.4,\n",
            "        \"Salinity\": 2.13,\n",
            "        \"Air temp\": 2.2,\n",
            "        \"Precip.\": 2.27\n",
            "      }\n",
            "    },\n",
            "    \"pounds\": {}\n",
            "  },\n",
            "  \"Whelk, Kellet's\": {\n",
            "    \"sci\": \"Kelletia kelletii\",\n",
            "    \"range\": \"The species was historically understood to have resided between Point Conception and Isla Asuncion, Baja California, but has been observed as far north as Monterey since the 1980s.\",\n",
            "    \"habitat\": \"Kellet’s whelk is primarily found in kelp forests and temperate rocky reef habitat, but also occurs in rocky shores and protected sandy beach habitats.\",\n",
            "    \"factors\": {\n",
            "      \"sens\": {\n",
            "        \"Habitat\": 2.67,\n",
            "        \"Prey\": 1.4,\n",
            "        \"Adult mobility\": 3.27,\n",
            "        \"Early dispersal\": 2.07,\n",
            "        \"Early survival\": 2.8,\n",
            "        \"Reproduction\": 2.0,\n",
            "        \"Spawning cycle\": 3.07,\n",
            "        \"Temperature\": 2.53,\n",
            "        \"Ocean acidification\": 3.8,\n",
            "        \"Pop. growth\": 3.53,\n",
            "        \"Stock status\": 1.93,\n",
            "        \"Other stressors\": 1.53\n",
            "      },\n",
            "      \"exp\": {\n",
            "        \"SST\": 2.07,\n",
            "        \"Ocean pH\": 3.87,\n",
            "        \"Bottom oxygen\": 2.87,\n",
            "        \"Upwelling\": 2.93,\n",
            "        \"Sea level\": 2.4,\n",
            "        \"Salinity\": 2.4,\n",
            "        \"Air temp\": 2.0,\n",
            "        \"Precip.\": 1.27\n",
            "      }\n",
            "    },\n",
            "    \"pounds\": {}\n",
            "  },\n",
            "  \"Whitefish, ocean\": {\n",
            "    \"sci\": \"Caulolatilus princeps\",\n",
            "    \"range\": \"Ocean whitefish have a large range along the eastern Pacific Ocean. They are found from Vancouver Island, British Columbia to Chile, including the Gulf of California but are rare north of Central California.\",\n",
            "    \"habitat\": \"Adults split their time between day and night habitats at depths of 18 to 68 m (60 to 223 ft); during the day they are commonly found in deep sand habitats and during the night in shallow high-relief structure or kelp beds and are most common at offshore Islands\",\n",
            "    \"factors\": {\n",
            "      \"sens\": {\n",
            "        \"Habitat\": 2.6,\n",
            "        \"Prey\": 2.33,\n",
            "        \"Adult mobility\": 2.75,\n",
            "        \"Early dispersal\": 2.2,\n",
            "        \"Early survival\": 2.6,\n",
            "        \"Reproduction\": 2.27,\n",
            "        \"Spawning cycle\": 2.75,\n",
            "        \"Temperature\": 2.2,\n",
            "        \"Ocean acidification\": 2.13,\n",
            "        \"Pop. growth\": 2.53,\n",
            "        \"Stock status\": 3.53,\n",
            "        \"Other stressors\": 2.07\n",
            "      },\n",
            "      \"exp\": {\n",
            "        \"SST\": 3.2,\n",
            "        \"Ocean pH\": 3.13,\n",
            "        \"Bottom oxygen\": 2.27,\n",
            "        \"Upwelling\": 2.47,\n",
            "        \"Sea level\": 2.27,\n",
            "        \"Salinity\": 1.93,\n",
            "        \"Air temp\": 2.0,\n",
            "        \"Precip.\": 1.53\n",
            "      }\n",
            "    },\n",
            "    \"pounds\": {}\n",
            "  }\n",
            "}"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "/usr/local/lib/python3.12/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed\n",
            "  warn(msg)\n"
          ]
        }
      ],
      "source": [
        "\"\"\"\n",
        "Sources\n",
        "-------\n",
        "1. Frawley et al. (2025) PLOS Climate, \"A collaborative climate vulnerability\n",
        "   assessment of California marine fishery species\".\n",
        "   Repo: https://github.com/thfrawley/California_State_CVA\n",
        "     - Final_Aggregated_Scoresheets_6.6.2024.csv  -> factors.sens / factors.exp\n",
        "     - All_Species_Profiles_6.6.2024.xlsx         -> sci / range / habitat\n",
        "2. Commercial landings by species-year (pounds) -> pounds\n",
        "   (CDFW Marine Landings Data System, or the NOAA FOSS landings API)\n",
        "\n",
        "Usage:  python build_cva_profiles.py > cva_profiles.json\n",
        "\"\"\"\n",
        "\n",
        "import io\n",
        "import json\n",
        "import re\n",
        "import sys\n",
        "\n",
        "import pandas as pd\n",
        "import requests\n",
        "\n",
        "REPO = \"https://raw.githubusercontent.com/thfrawley/California_State_CVA/main\"\n",
        "SCORES_URL = f\"{REPO}/Final_Aggregated_Scoresheets_6.6.2024.csv\"\n",
        "PROFILES_URL = f\"{REPO}/All_Species_Profiles_6.6.2024.xlsx\"\n",
        "\n",
        "# Which exposure scenario to embed: \"exposure_Near\" (2030-2060) or\n",
        "# \"exposure_Far\" (2070-2100).\n",
        "EXPOSURE_SCENARIO = \"exposure_Far\"\n",
        "\n",
        "# shotern names for JSON\n",
        "SENS_LABELS = {\n",
        "    \"habitat_specificity\": \"Habitat\",\n",
        "    \"prey_specificity\": \"Prey\",\n",
        "    \"adult_mobility\": \"Adult mobility\",\n",
        "    \"dispersal_of_early_life_stages\": \"Early dispersal\",\n",
        "    \"early_life_history_survival_and_settlement\": \"Early survival\",\n",
        "    \"complexity_in_reproductive_strategy\": \"Reproduction\",\n",
        "    \"spawing_cycle\": \"Spawning cycle\",          # sic: typo is in the source\n",
        "    \"sensitivity_to_temperature\": \"Temperature\",\n",
        "    \"sensitivity_to_OA\": \"Ocean acidification\",\n",
        "    \"population_growth_rate\": \"Pop. growth\",\n",
        "    \"stock_size_or_status\": \"Stock status\",\n",
        "    \"other_stressors\": \"Other stressors\",\n",
        "}\n",
        "EXP_LABELS = {\n",
        "    \"mean_SST\": \"SST\",\n",
        "    \"mean_pH\": \"Ocean pH\",\n",
        "    \"subsurface_oxygen\": \"Bottom oxygen\",\n",
        "    \"phenology_upwelling\": \"Upwelling\",\n",
        "    \"sea_level_rise\": \"Sea level\",\n",
        "    \"mean_salinity\": \"Salinity\",\n",
        "    \"mean_air_temp\": \"Air temp\",\n",
        "    \"mean_percipitation\": \"Precip.\",   #sic\n",
        "}\n",
        "\n",
        "# consolidate species naming\n",
        "SPECIES_KEYS = {\n",
        "    \"California_Barracuda\": (\"Barracuda, California\", \"Pacific Barracuda\"),\n",
        "    \"Pacific_Bonito\": (\"Bonito, Pacific\", \"Pacific Bonito\"),\n",
        "    \"Dungeness_Crab\": (\"Crab, Dungeness\", \"Dungeness Crab\"),\n",
        "    \"White_Croaker\": (\"Croaker, white\", \"White Croaker\"),\n",
        "    \"CA_Halibut\": (\"Halibut, California\", \"California Halibut\"),\n",
        "    \"Jacksmelt\": (\"Jacksmelt\", \"Jacksmelt\"),\n",
        "    \"Spiny_Lobster\": (\"Lobster, California spiny\", \"Spiny Lobster\"),\n",
        "    \"Ridgeback_Prawn\": (\"Prawn, ridgeback\", \"Ridgeback Prawn\"),\n",
        "    \"Spot_Prawn\": (\"Prawn, spot\", \"Spot Prawn\"),\n",
        "    \"Red_Sea_Urchin\": (\"Sea urchin, red\", \"Red Sea Urchin\"),\n",
        "    \"White_Seabass\": (\"Seabass, white\", \"White Seabass\"),\n",
        "    \"Pacific_Angel_Shark\": (\"Shark, Pacific angel\", \"Pacific Angel Shark\"),\n",
        "    \"Brown_Smoothhound_Shark\": (\"Shark, brown smoothhound\", \"Brown Smoothhound Shark\"),\n",
        "    \"CA_Sheephead\": (\"Sheephead, California\", \"California Sheephead\"),\n",
        "    \"Market_Squid\": (\"Squid, market\", \"Market Squid\"),\n",
        "    \"Barred_Surf_Perch\": (\"Surfperch, barred\", \"Barred Surfperch\"),\n",
        "    \"Redtail_Surfperch\": (\"Surfperch, redtail\", \"Redtail Surfperch\"),\n",
        "    \"Kellet's_Whelk\": (\"Whelk, Kellet's\", \"Kellet's Whelk\"),\n",
        "    \"Ocean_Whitefish\": (\"Whitefish, ocean\", \"Ocean Whitefish\"),\n",
        "}\n",
        "\n",
        "# genus + species\n",
        "SCI_NAME = {\n",
        "    \"Market Squid\": \"Doryteuthis opalescens\",\n",
        "    \"California Halibut\": \"Paralichthys californicus\",\n",
        "}\n",
        "\n",
        "\n",
        "def snip(text, budget=250):\n",
        "    \"\"\"Keep whole sentences up to a character budget.\n",
        "    \"\"\"\n",
        "    text = re.sub(r\"\\s+\", \" \", str(text)).strip()\n",
        "    kept = \"\"\n",
        "    for part in re.split(r\"(?<=[.!?]) \", text):\n",
        "        if kept and len(kept) + len(part) + 1 > budget:\n",
        "            break\n",
        "        kept = f\"{kept} {part}\".strip()\n",
        "    if not kept:\n",
        "        kept = text[:budget].rsplit(\" \", 1)[0]\n",
        "    return kept + (\" \\u2026\" if kept != text else \"\")\n",
        "\n",
        "\n",
        "def load_scores():\n",
        "    df = pd.read_csv(io.StringIO(requests.get(SCORES_URL).text))\n",
        "    # Final_Score, not Initial_Weighted_Mean - carries expert values\n",
        "    df = df[[\"Species\", \"Sensitivity_or_Exposure\", \"Description\", \"Final_Score\"]]\n",
        "    return df\n",
        "\n",
        "\n",
        "def load_narratives():\n",
        "    raw = requests.get(PROFILES_URL).content\n",
        "    df = pd.read_excel(io.BytesIO(raw), sheet_name=\"Tabular_Form_Species_Narratives\")\n",
        "    df.columns = [c.strip() for c in df.columns]\n",
        "    df[\"ATTRIBUTE\"] = df[\"ATTRIBUTE\"].astype(str).str.strip()\n",
        "    df[\"PROMPT\"] = df[\"PROMPT\"].astype(str).str.strip()\n",
        "    return df\n",
        "\n",
        "\n",
        "def species_rows(df, profile_name):\n",
        "    \"\"\"SPECIES cells look like 'Pacific Barracuda (Sphyraena argentea)'.\"\"\"\n",
        "    return df[df[\"SPECIES\"].astype(str).str.strip().str.startswith(profile_name)]\n",
        "\n",
        "\n",
        "def narrative(rows, attribute, prompt_startswith):\n",
        "    hit = rows[(rows[\"ATTRIBUTE\"] == attribute)\n",
        "               & rows[\"PROMPT\"].str.startswith(prompt_startswith)]\n",
        "    return snip(hit.iloc[0][\"DATA\"]) if len(hit) else None\n",
        "\n",
        "\n",
        "def sci_name(rows, profile_name):\n",
        "    if profile_name in SCI_NAME:\n",
        "        return SCI_NAME[profile_name]\n",
        "    cell = str(rows.iloc[0][\"SPECIES\"]).strip()\n",
        "    m = re.search(r\"\\(([^()]+)\\)\", cell)\n",
        "    return m.group(1) if m else cell[len(profile_name):].strip()\n",
        "\n",
        "\n",
        "def build(landings=None):\n",
        "    scores, narr = load_scores(), load_narratives()\n",
        "    out = {}\n",
        "    for slug, (key, profile_name) in SPECIES_KEYS.items():\n",
        "        sub = scores[scores[\"Species\"] == slug]\n",
        "        rows = species_rows(narr, profile_name)\n",
        "\n",
        "        sens = {\n",
        "            SENS_LABELS[r.Description]: float(r.Final_Score)\n",
        "            for r in sub[sub[\"Sensitivity_or_Exposure\"] == \"sensitivity\"].itertuples()\n",
        "            if r.Description in SENS_LABELS\n",
        "        }\n",
        "        exp = {\n",
        "            EXP_LABELS[r.Description]: float(r.Final_Score)\n",
        "            for r in sub[sub[\"Sensitivity_or_Exposure\"] == EXPOSURE_SCENARIO].itertuples()\n",
        "            if r.Description in EXP_LABELS\n",
        "        }\n",
        "\n",
        "        out[key] = {\n",
        "            \"sci\": sci_name(rows, profile_name),\n",
        "            \"range\": narrative(rows, \"Sensitivity to temp\",\n",
        "                               \"What is the range of the stock?\"),\n",
        "            \"habitat\": narrative(rows, \"Habitat specificity\",\n",
        "                                 \"What are the habitat requirements for adults?\"),\n",
        "            # dict ordering is the rubric order, not alphabetical\n",
        "            \"factors\": {\n",
        "                \"sens\": {k: sens[k] for k in SENS_LABELS.values() if k in sens},\n",
        "                \"exp\": {k: exp[k] for k in EXP_LABELS.values() if k in exp},\n",
        "            },\n",
        "            \"pounds\": (landings or {}).get(key, {}),\n",
        "        }\n",
        "    return out\n",
        "\n",
        "\n",
        "if __name__ == \"__main__\":\n",
        "    json.dump(build(), sys.stdout, indent=2,\n",
        "              ensure_ascii=False)\n",
        ""
      ]
    }
  ]
}